# Whatever it is you want to do other run demos, it should be forwarded to the
# to top-level directory
.PHONY: all tortoise

#: the default target - same as running "check"
all:
	$(MAKE) -C .. tortoise
%:
	$(MAKE) -C .. $@
