# Whatever it is you want to do, it should be forwarded to the
# to top-level irectories
.PHONY: all check check-quick test test-quick

#: Run tests
check:
	$(MAKE) -C .. check

#: same as check
all: check
#: same as check
check-quick: check
#: same as check
test: check
